name: ImageFireworksPro
version: '${project.version}'
main: me.lukyn76.imagefireworkspro.ImageFireworksPro
api-version: '1.20'
commands:
  imagefireworkspro:
    description: Give custom image fireworks to players.
    permission: imagefireworkspro.command
    aliases: [ifp]
    default: op
